version: "3.3"

services:
    web:
        container_name: ${CONTAINER_NAME}
        restart: always
        build:
            dockerfile: .docker/web/Dockerfile
            context: ..
        volumes:
            - ../:/var/www
        extra_hosts:
            - host.docker.internal:host-gateway
        entrypoint: ["/var/www/.docker/entrypoint.sh"]
        expose:
            - "${WEB_PORT:-80}"
            - "${VITE_PORT:-5173}"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${CONTAINER_NAME}.entrypoints=${ENTRYPOINT}"
            - "traefik.http.routers.${CONTAINER_NAME}.rule=Host(`${DOMAIN}`)"
            - "traefik.http.routers.${CONTAINER_NAME}.service=${CONTAINER_NAME}"
            - "traefik.http.services.${CONTAINER_NAME}.loadbalancer.server.port=${WEB_PORT:-80}"
            - "traefik.http.routers.${CONTAINER_NAME}.tls=${TLS:-false}"
            - "traefik.http.routers.${CONTAINER_NAME}.tls.certresolver=${CERT_RESOLVER:-letsencrypt}"
            - "traefik.http.routers.${CONTAINER_NAME}-vite.entrypoints=${ENTRYPOINT_VITE}"
            - "traefik.http.routers.${CONTAINER_NAME}-vite.rule=Host(`${DOMAIN}`)"
            - "traefik.http.routers.${CONTAINER_NAME}-vite.service=${CONTAINER_NAME}-vite"
            - "traefik.http.services.${CONTAINER_NAME}-vite.loadbalancer.server.port=${VITE_PORT:-5173}"
            - "traefik.http.routers.${CONTAINER_NAME}-vite.tls=${TLS:-false}"
            - "traefik.http.routers.${CONTAINER_NAME}-vite.tls.certresolver=${CERT_RESOLVER:-letsencrypt}"
        networks:
            - proxy
        tty: true

networks:
    proxy:
        external: true
